db.characters.insert([{
    name: 'John',
    race: 'Human',
    class: 'Rogue',
    level: 12,
    strength: 12,
    agility: 32,
    intellect: 11,
    ishidden: false,
    imagename: null
}, {
    name: 'Svend',
    race: 'Dwarf',
    class: 'Blacksmith',
    level: 12,
    strength: 12,
    agility: 32,
    intellect: 11,
    ishidden: false,
    imagename: null
}, {
    name: 'Peter',
    race: 'Human',
    class: 'Shaman',
    level: 12,
    strength: 12,
    agility: 32,
    intellect: 11,
    ishidden: true,
    imagename: null
}]);